import{a as y,S as L,i as f}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const v="44070637-4c17cd33bb35071a705149900";async function m(e,t=1,s=15){const{data:n}=await y.get("https://pixabay.com/api/?",{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:t}});return n}const w=new L(".gallery a",{captionsData:"alt",captionDelay:250});function b(){return'<div class="loader"></div>'}function M(){f.warning({title:"Fill in the search field",position:"topRight"})}function g(){f.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function q(e){return`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" class="foto" height="148" width="360">
      <div class="info" >
        <p class="icon">Likes: ${e.likes} </p>
        <p class="icon">Views: ${e.views}</p>
        <p class="icon">Comments: ${e.comments}</p>
        <p class="icon">Downloads: ${e.downloads}</p>
      </div>
    </a>`}function H(e){return e.map(t=>q(t)).join("")}function S(){const e=document.createElement("p");e.textContent="We're sorry, but you've reached the end of search results.",e.style.textAlign="center",e.style.marginTop="20px",e.classList.add("end-of-results-message"),document.body.appendChild(e)}const p=document.querySelector(".form"),a=document.querySelector(".gallery"),i=document.querySelector(".div-load");let l=1;const d=15;let R=0;p.addEventListener("submit",async e=>{e.preventDefault();const t=e.target.elements.searchInput.value.trim();if(t===""){M();return}O(),a.innerHTML=b(),l=1,i.classList.add("load-more-hidden");try{const s=await m(t,l,d);R=Math.ceil(s.totalHits/d),h(s)}catch(s){console.error("error:",s),g()}});function h(e,t=!1){if(!e||e.total===0){g(),a.innerHTML="",i.classList.add("load-more-hidden");return}const s=e.hits;console.log("response",e);const n=H(s);t?a.innerHTML+=n:a.innerHTML=n,a.children.length<e.totalHits?i.classList.remove("load-more-hidden"):(i.classList.add("load-more-hidden"),S()),w.refresh()}i.addEventListener("click",x);async function x(){l+=1;const e=p.elements.searchInput.value.trim();u();try{const t=await m(e,l,d);h(t,!0),E()}catch(t){console.error("error:",t)}finally{u()}}function u(){i.classList.toggle("hidden")}function E(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function O(){const e=document.querySelector(".end-of-results-message");e&&e.remove()}
//# sourceMappingURL=commonHelpers.js.map
